project:
  type: book
license: CC BY-SA
latex-auto-install: true

lang: fr
language:
  toc-title-document: "Table des matières"
  title-block-author-plural: "Auteurs"
  repo-action-links-issue: "Signaler un problème ou<br>formuler une suggestion"
crossref:
  lof-title: "Liste des figures"
  lot-title: "Listes des tableaux"
  fig-prefix: figure
  tbl-prefix: tableau
  sec-prefix: section
  eq-prefix: équation
  fig-title: Figure
  tbl-title: Tableau
  eq-title: Équation
book:
  title: "Animint2 dans R pour la visualisation de données"
  repo-url: https://github.com/animint/animint-manual-fr
  repo-actions: [edit, issue, source]
  repo-subdir: Chapitres
  favicon: Figures/favicon.ico
  cover-image: Figures/logo.png
  downloads: [pdf]
  sidebar:
    style: "floating"
    collapse-level: 1
    border: true
    search: true
  page-footer:
    left: |
      All content licensed under [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) <br> &copy; Toby Dylan Hocking.
    center: "[GitHub](https://github.com/animint/animint2) | [Galerie](https://animint.github.io/gallery-fr)"
    right: Built with [Quarto](https://quarto.org/).
    background: "#f8f9fa"
  chapters:
    - index.qmd
    - part: "Fonctions de base"
      chapters:
      - Ch02/Ch02-viz.qmd
      - Ch03/Ch03-viz.qmd
      - Ch04/Ch04-viz.qmd
      - Ch05/Ch05-viz.qmd
      - Ch06/Ch06-viz.qmd
      - Ch07/Ch07-viz.qmd
    - part: "Exemples avancés"
      chapters:
      - Ch08/Ch08-viz.qmd
  appendices:
      - Ch99/Ch99-viz.qmd

bibliography: refs.bib

format:
  html:
    theme:
      light: [default]
    page-layout: full
    fontsize: "15px"
    linestretch: 1.6
    smooth-scroll: true
    toc-depth: 3
    code-link: true
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
    code-overflow: wrap
    reference-location: margin
    mermaid:
      theme: neutral

  # see https://pandoc.org/MANUAL.html for all options
  pdf:
    documentclass: style/krantz
    classoption: krantz2
    lof: false
    lot: false
    toc: false
    toc-depth: 2
    fig-cap-location: bottom
    tbl-cap-location: top
    urlcolor: "blue"
    linkcolor: "black"
    biblio-style: apalike
    keep-tex: true
    code-block-bg: "#f2f2f2"
    code-block-border-left: "#f2f2f2"
    code-overflow: wrap
    mermaid:
      theme: neutral
    include-in-header:
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body:
      text: |
        \printindex

knitr:
  opts_chunk:
    cache: true
    cache.lazy: false
    dpi: 600
    fig.width: 5.5
    fig.height: 3
    out.width: "100%"
    split: true
    R.options:
      knitr.graphics.auto_pdf: true
      datatable.print.nrows: 10
      datatable.print.class: false
      datatable.print.keys: false
      datatable.print.trunc.cols: TRUE
